name: Test and Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./static-algorithm
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          python-version: '3.12'
      - name: Install dependencies
        run: |
          poetry check
          poetry install
      - name: Run Ruff
        run: poetry run ruff check -e --output-format=github .
      - uses: jakebailey/pyright-action@v2
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./static-algorithm
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          python-version: '3.12'
      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests
        run: poetry run pytest
