name: Test and Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./static-algorithm
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          python-version: '3.12'
      - name: Install dependencies
        run: make install
      - name: Run Ruff
        continue-on-error: true
        run: make ruff
      - name: Export PATH
        run: |
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
          alias pyright=basedpyright
      - name: Run Pyright
        uses: jakebailey/pyright-action@v2

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./static-algorithm
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          python-version: '3.12'
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make test
